version: "3.8"

services:
  postgres:
    image: postgres:13.1-alpine
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - connection
    environment:
      - POSTGRES_PASSWORD=local-password
      - POSTGRES_DB=software-engineering

  django:
    build:
      context: djackend
    command: >
      bash -c "python3 manage.py collectstatic --noinput &&
              python3 manage.py migrate &&
              python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
    networks:
      - connection
    ports:
      - "8000:8000"
    volumes:
      - ./djackend:/app
    environment:
<<<<<<< Updated upstream
      - DATABASE_URL=postgres://postgres:local-password@postgres/software-engineering
=======
      # - DATABASE_URL=psql://postgres:local-password@postgres/software-engineering
      - NAME=software-engineering
      - USER=postgres
      - PASSWORD=local-password
      - HOST=postgres
      - PORT=5432
>>>>>>> Stashed changes

  react:
    build:
      context: frontend
    command: npm start
    depends_on:
      - django
    networks:
      - connection
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules/
    environment:
      - BACKEND_URL=http://express:4200

networks:
  connection:

volumes:
  database:
  